# This file was generated by the package-script.sh script.
class CompareDirs < Formula
  desc "Recursively compares two directories and reports differences in existence, size, timestamps, and checksums."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/compare-dirs-v1.2.3/scripts-compare-dirs-v1.2.3.tar.gz"
  sha256 "65d53cdcbc357913235a6280aab2d6a990e76ea9dff9c4cdb1afb16342166871"
  version "1.2.3"
  license "MIT"
  depends_on "bash"
  def install
    bin.install "compare-dirs.sh" => "compare-dirs"
    inreplace bin/"compare-dirs", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"compare-dirs", :executable?
  end
end
