# This file was generated by the package-script.sh script.
class CompareDirs < Formula
  desc "Recursively compares two directories and reports differences in existence, size, timestamps, and checksums."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/compare-dirs-v1.2.2/scripts-compare-dirs-v1.2.2.tar.gz"
  sha256 "acd6046e370685c1c6a8147137d3e2bdff4da03c1fea567156350d6a518c8292"
  version "1.2.2"
  license "MIT"
  depends_on "bash"
  def install
    bin.install "compare-dirs.sh" => "compare-dirs"
    inreplace bin/"compare-dirs", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"compare-dirs", :executable?
  end
end
