# This file was generated by the package-script.sh script.
class DmarcReport < Formula
  desc "Aggregates a folder of DMARC RUA reports (.xml.gz/.zip) into one overall report, tracking policy changes over time and flagging unenforced domains, unaligned senders, DNS/DKIM errors, and spoofing."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/dmarc-report-v1.0.0/scripts-dmarc-report-v1.0.0.tar.gz"
  sha256 "60867a9c4a142ec83a630ab384ee47edc5b1efe3caf80ada774167519282c76b"
  version "1.0.0"
  license "MIT"
  depends_on "libxml2"
  def install
    bin.install "dmarc-report.sh" => "dmarc-report"
  end

  test do
    assert_predicate bin/"dmarc-report", :executable?
  end
end
