# This file was generated by the package-script.sh script.
class DmarcReport < Formula
  desc "Aggregates a folder of DMARC RUA reports (.xml.gz/.zip) into one overall report, tracking policy changes over time and flagging unenforced domains, unaligned senders, DNS/DKIM errors, and spoofing (grouped into subnets with per-range country lookup, or totalled by country)."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/dmarc-report-v1.2.0/scripts-dmarc-report-v1.2.0.tar.gz"
  sha256 "db58f311eee4fd0201eb5d75e6e6f03c1022b40fc5efc615f0295231993fcf28"
  version "1.2.0"
  license "MIT"
  depends_on "bash"
  depends_on "curl"
  depends_on "jq"
  depends_on "libxml2"
  def install
    bin.install "dmarc-report.sh" => "dmarc-report"
    inreplace bin/"dmarc-report", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"dmarc-report", :executable?
  end
end
