# This file was generated by the package-script.sh script.
class DoviActiveArea < Formula
  desc "Reports the Dolby Vision L5 active area of Matroska files, and on request zeroes it by rewriting the RPU in place, so a display stops cropping or letterboxing a picture that already fills its frame. Requires the external tool 'dovi_tool', which Debian has no package for."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/dovi-active-area-v2.0.0/scripts-dovi-active-area-v2.0.0.tar.gz"
  sha256 "8df0a02761b97e9be5a74606acd2fa81b6fbe62a945bd86a0ede224214a663d3"
  version "2.0.0"
  license "MIT"
  depends_on "bash"
  depends_on "ffmpeg"
  depends_on "jq"
  depends_on "mediainfo"
  depends_on "mkvtoolnix"
  depends_on "dovi_tool"
  def install
    bin.install "dovi-active-area.sh" => "dovi-active-area"
    etc.install "dovi-active-area.conf" => "dovi-active-area.conf"
    inreplace bin/"dovi-active-area", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"dovi-active-area", :executable?
  end
end
