# This file was generated by the publish-script.sh script.
class InstallDependency < Formula
  desc "A cross-platform script to install a given package on macOS or Debian-based Linux."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.1.0"
  sha256 "4a8dcb32c2edd98a5aa9fd0929a85e72ee5cc42a995ffda60d30a58313fdc2f8"



  def install
    bin.install "system/install-dependency.sh" => "install-dependency"
  end
end
