# This file was generated by the publish.sh script.
class InstallDependency < Formula
  desc "A cross-platform script to install a given package on macOS or Debian-based Linux."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.0.1"
  sha256 "2cd46bb41f3b25d2f4315d0908e4ae962a39cb656f4156a65e30593166eba58c"



  def install
    # This line installs the script into Homebrew's binary directory.
    # The script is installed from its relative path in the tarball.
    bin.install "system/install-dependency.sh" => "install-dependency"
  end
end
