# This file was generated by the package-script.sh script.
class InstallDependency < Formula
  desc "Handles the installation of a specified package on macOS (via Homebrew) or Debian-based Linux (via apt-get)."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.4.0"
  sha256 "919128947ddac574e7a9f0eec7e2735522eff37dd2fd4360f40bedfac6ec86eb"
  License: "MIT"
  def install
    bin.install "system/install-dependency.sh" => "install-dependency"
    
  end
end
