# This file was generated by the package-script.sh script.
class LinkSeries < Formula
  desc "Links episodes from a download folder into a series' library folder, taking the show and season from the destination directory itself, so manually acquired releases join the library without a second copy of the file."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/link-series-v1.0.0/scripts-link-series-v1.0.0.tar.gz"
  sha256 "386d7ace94b52259d9af8852e60325bf301b614e988850ae879fe12b9398dc67"
  version "1.0.0"
  license "MIT"
  depends_on "bash"
  def install
    bin.install "link-series.sh" => "link-series"
    etc.install "link-series.conf" => "link-series.conf"
    inreplace bin/"link-series", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"link-series", :executable?
  end
end
