# This file was generated by the package-script.sh script.
class LocalBackup < Formula
  desc "A generic script to create and automatically prune rsync-based system backups."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/archive/refs/tags/local-backup-v1.0.2.tar.gz"
  sha256 "461e9f2d4293d03d197dac07806d688421db6182823a7e4bd2cf547199ea536f"
  license "MIT"
  depends_on "rsync"
  depends_on "ionice"
  def install
    bin.install "./system/local-backup.sh" => "local-backup"
    etc.install "./conf/local-backup.conf" => "local-backup.conf"
  end

  test do
    assert_predicate bin/"local-backup", :executable?
  end
end
