# This file was generated by the package-script.sh script.
class LocalBackup < Formula
  desc "A generic script to create and automatically prune rsync-based system backups."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/local-backup-v1.4.0/scripts-local-backup-v1.4.0.tar.gz"
  sha256 "88857e811712c10fa4179ad766083049eb6207c2cfde3b10e02847ef58f86c2b"
  version "1.4.0"
  license "MIT"
  depends_on "bash"
  depends_on "rsync"
  def install
    bin.install "local-backup.sh" => "local-backup"
    etc.install "local-backup.conf" => "local-backup.conf"
    inreplace bin/"local-backup", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"local-backup", :executable?
  end
end
