# This file was generated by the package-script.sh script.
class MemoryPressureAlert < Formula
  desc "Warns while a Mac is filling up — swap growing and free memory falling — rather than once it has already stalled, and names the heaviest applications by resident plus compressed memory."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/memory-pressure-alert-v1.0.0/scripts-memory-pressure-alert-v1.0.0.tar.gz"
  sha256 "23e9ae33c5b90f62e68522ddb1e9136c7a506b5a8dcded2500ff5b89bbfad53d"
  version "1.0.0"
  license "MIT"
  def install
    bin.install "memory-pressure-alert.sh" => "memory-pressure-alert"
    etc.install "memory-pressure-alert.conf" => "memory-pressure-alert.conf"
  end

  test do
    assert_predicate bin/"memory-pressure-alert", :executable?
  end
end
