# This file was generated by the package-script.sh script.
class MemoryPressureAlert < Formula
  desc "Warns while a Mac is filling up — swap growing and memory use climbing — rather than once it has already stalled, and names the heaviest applications by resident plus compressed memory."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/memory-pressure-alert-v1.1.0/scripts-memory-pressure-alert-v1.1.0.tar.gz"
  sha256 "cf2d9d0383260ea80bbf2805a5838b9a55122fc2c9da61f153c1334495f391f3"
  version "1.1.0"
  license "MIT"
  def install
    bin.install "memory-pressure-alert.sh" => "memory-pressure-alert"
    etc.install "memory-pressure-alert.conf" => "memory-pressure-alert.conf"
  end

  test do
    assert_predicate bin/"memory-pressure-alert", :executable?
  end
end
