# This file was generated by the package-script.sh script.
class NormalizeReleaseNames < Formula
  desc "Brings episode filenames to one spelling — dots for separators, lower case, and the season and episode as S01E02 — so that sidecar pairing, library linking and episode parsers all match the same names. Renames subtitles alongside their video and refuses a rename whose destination is taken."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/normalize-release-names-v1.0.0/scripts-normalize-release-names-v1.0.0.tar.gz"
  sha256 "59bf19ac332364be7aad5ff17197aae3c57be41b1f704c6990ab3b3b7fbb6410"
  version "1.0.0"
  license "MIT"
  depends_on "bash"
  def install
    bin.install "normalize-release-names.sh" => "normalize-release-names"
    etc.install "normalize-release-names.conf" => "normalize-release-names.conf"
    inreplace bin/"normalize-release-names", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"normalize-release-names", :executable?
  end
end
