# This file was generated by the package-script.sh script.
class PackageScript < Formula
  desc "A generic package-file generator for Homebrew and Debian."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.4.0"
  sha256 "919128947ddac574e7a9f0eec7e2735522eff37dd2fd4360f40bedfac6ec86eb"
  License: "MIT"
  depends_on "awk"
  def install
    bin.install "system/package-script.sh" => "package-script"
    
  end
end
