# This file was generated by the package-script.sh script.
class PhotoBackup < Formula
  desc "A robust script for backing up photo collections from multiple sources to a remote server using rsync."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/photo-backup-v2.1.2/scripts-photo-backup-v2.1.2.tar.gz"
  sha256 "b9a521ff0076e78d8b961e8172315f352c9f00e354071af44ec50da03604d6f7"
  version "2.1.2"
  license "MIT"
  depends_on "rsync"
  def install
    bin.install "photo-backup.sh" => "photo-backup"
    etc.install "photo-backup.conf" => "photo-backup.conf"
  end

  test do
    assert_predicate bin/"photo-backup", :executable?
  end
end
