# This file was generated by the package-script.sh script.
class PhotoBackup < Formula
  desc "A robust script for backing up photo collections from multiple sources to a remote server using rsync."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.2.3"
  sha256 "09b0fe5e8565a63430e0badd9e8734f9a4eeb43183a988b2a92465ddeeb5512c"



  def install
    bin.install "photography/photo-backup.sh" => "photo-backup"
    etc.install "./conf/photo-backup.conf" => "photo-backup.conf"
  end
end
