# This file was generated by the package-script.sh script.
class PhotoBackup < Formula
  desc "A robust script for backing up photo collections from multiple sources to a remote server using rsync."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/photo-backup-v2.2.0/scripts-photo-backup-v2.2.0.tar.gz"
  sha256 "617a24a611c12445b7aa492f75a5db94cdc7586cd3ca0a29c4979a6d64d5b974"
  version "2.2.0"
  license "MIT"
  depends_on "rsync"
  def install
    bin.install "photo-backup.sh" => "photo-backup"
    etc.install "photo-backup.conf" => "photo-backup.conf"
  end

  test do
    assert_predicate bin/"photo-backup", :executable?
  end
end
