# This file was generated by the package-script.sh script.
class PruneOrphanedTorrents < Formula
  desc "Finds orphaned media files left by *arr hard-linking and interactively removes the corresponding torrents from Deluge."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/prune-orphaned-torrents-v1.1.0/scripts-prune-orphaned-torrents-v1.1.0.tar.gz"
  sha256 "986b7b902174c658924c5cdb208dc9398ceef3b042293c1f6bf4516249509da8"
  version "1.1.0"
  license "MIT"
  depends_on "curl"
  depends_on "jq"
  def install
    bin.install "prune-orphaned-torrents.sh" => "prune-orphaned-torrents"
    etc.install "prune-orphaned-torrents.conf" => "prune-orphaned-torrents.conf"
  end

  test do
    assert_predicate bin/"prune-orphaned-torrents", :executable?
  end
end
