# This file was generated by the package-script.sh script.
class PruneOrphanedTorrents < Formula
  desc "Finds orphaned media files left by *arr hard-linking and interactively removes the corresponding torrents from Deluge."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/prune-orphaned-torrents-v1.2.0/scripts-prune-orphaned-torrents-v1.2.0.tar.gz"
  sha256 "8b7af5f835bc2739c0c34f0092b6eb81a7d579c7f676169fd4f673e26dda2b42"
  version "1.2.0"
  license "MIT"
  depends_on "curl"
  depends_on "jq"
  def install
    bin.install "prune-orphaned-torrents.sh" => "prune-orphaned-torrents"
    etc.install "prune-orphaned-torrents.conf" => "prune-orphaned-torrents.conf"
  end

  test do
    assert_predicate bin/"prune-orphaned-torrents", :executable?
  end
end
