# This file was generated by the package-script.sh script.
class PruneOrphanedTorrents < Formula
  desc "Finds orphaned media files left by *arr hard-linking and interactively removes the corresponding torrents from Deluge."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/prune-orphaned-torrents-v1.0.1/scripts-prune-orphaned-torrents-v1.0.1.tar.gz"
  sha256 "658383989106eaa20adcda2a20e2176cc994a975354d9426ff18d74cd0464767"
  version "1.0.1"
  license "MIT"
  depends_on "curl"
  depends_on "jq"
  def install
    bin.install "prune-orphaned-torrents.sh" => "prune-orphaned-torrents"
    etc.install "prune-orphaned-torrents.conf" => "prune-orphaned-torrents.conf"
  end

  test do
    assert_predicate bin/"prune-orphaned-torrents", :executable?
  end
end
