# This file was generated by the publish.sh script.
class PublishScript < Formula
  desc "A powerful, generic script that automates the process of publishing a command-line utility to both a Homebrew tap and a Debian APT repository. It is designed to be run from a CI/CD workflow, such as GitHub Actions, and is configured entirely through environment variables."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.0.2"
  sha256 "269a08359474ffbc7bf2b0f99a9e0283f6ad1204d2bb44e1b30c3e91c041910e"



  def install
    # This line installs the script into Homebrew's binary directory.
    # The script is installed from its relative path in the tarball.
    bin.install "system/publish-script.sh" => "publish-script"
  end
end
