# This file was generated by the publish-script.sh script.
class PublishScript < Formula
  desc "A powerful, generic script that automates the process of publishing a command-line utility to both a Homebrew tap and a Debian APT repository. It is designed to be run from a CI/CD workflow, such as GitHub Actions, and is configured entirely through environment variables."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.1.0"
  sha256 "4a8dcb32c2edd98a5aa9fd0929a85e72ee5cc42a995ffda60d30a58313fdc2f8"



  def install
    bin.install "system/publish-script.sh" => "publish-script"
  end
end
