# This file was generated by the publish.sh script.
class Publish < Formula
  desc "A powerful, generic script that automates the process of publishing a command-line utility to both a Homebrew tap and a Debian APT repository. It is designed to be run from a CI/CD workflow, such as GitHub Actions, and is configured entirely through environment variables."
  homepage "https://github.com/jmerhar/scripts"
  url "https://api.github.com/repos/jmerhar/scripts/tarball/v1.0.2"
  sha256 "cbcb45210bbcf1e6a796a395a6a977eb206b58e0df387b0178971c995eb89e2d"



  def install
    # This line installs the script into Homebrew's binary directory.
    # The script is installed from its relative path in the tarball.
    bin.install "system/publish.sh" => "publish"
  end
end
