# This file was generated by the package-script.sh script.
class RemoveSidecars < Formula
  desc "A script to find and delete \"sidecar\" files when a corresponding RAW photo file exists."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/remove-sidecars-v1.7.3/scripts-remove-sidecars-v1.7.3.tar.gz"
  sha256 "e1974d01e10a671a24a5d08506ce8b34ebda833f747fa08f1c73483c2b034b6e"
  version "1.7.3"
  license "MIT"
  depends_on "bash"
  def install
    bin.install "remove-sidecars.sh" => "remove-sidecars"
    inreplace bin/"remove-sidecars", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"remove-sidecars", :executable?
  end
end
