# This file was generated by the package-script.sh script.
class RemoveSidecars < Formula
  desc "A script to find and delete \"sidecar\" files when a corresponding RAW photo file exists."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/remove-sidecars-v1.6.1/scripts-remove-sidecars-v1.6.1.tar.gz"
  sha256 "fbbcecf5b7ba692780041e6c3967f713bc2a8b6c19e8697ab0290909d7300dc4"
  version "1.6.1"
  license "MIT"
  depends_on "perl"
  def install
    bin.install "remove-sidecars.pl" => "remove-sidecars"
  end

  test do
    assert_predicate bin/"remove-sidecars", :executable?
  end
end
