# This file was generated by the package-script.sh script.
class SubtitleReport < Formula
  desc "Reports on subtitle coverage for a media library, detecting embedded tracks and sidecar files and breaking down counts by language and source."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/subtitle-report-v1.1.1/scripts-subtitle-report-v1.1.1.tar.gz"
  sha256 "a61e2ab6a7c4e184764807fa4bc7ea8d370e8c2dfff823228359dac82a25b217"
  version "1.1.1"
  license "MIT"
  depends_on "bash"
  depends_on "ffmpeg"
  def install
    bin.install "subtitle-report.sh" => "subtitle-report"
    etc.install "subtitle-report.conf" => "subtitle-report.conf"
    inreplace bin/"subtitle-report", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"subtitle-report", :executable?
  end
end
