# This file was generated by the package-script.sh script.
class SubtitleSync < Formula
  desc "Resynchronizes drifting subtitles to a video's speech using a Whisper transcript as reference and alass for segment-aware alignment (handles ad-break, global-offset, and speed drift). Requires the external tools 'alass' and 'whisper-ctranslate2' on PATH."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/subtitle-sync-v1.1.3/scripts-subtitle-sync-v1.1.3.tar.gz"
  sha256 "265b3d430f3aa082ccfdd636711b2741f74a68dfd56e202be1806dd9c39382dd"
  version "1.1.3"
  license "MIT"
  depends_on "bash"
  depends_on "ffmpeg"
  def install
    bin.install "subtitle-sync.sh" => "subtitle-sync"
    etc.install "subtitle-sync.conf" => "subtitle-sync.conf"
    inreplace bin/"subtitle-sync", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"subtitle-sync", :executable?
  end
end
