# This file was generated by the package-script.sh script.
class TranscodeAudio < Formula
  desc "Re-encodes the audio of Matroska files to a codec the playback chain can decode (AC-3 by default, for a receiver that cannot take Dolby Digital Plus), in one ffmpeg pass that copies the video, subtitles and chapters and keeps every audio track with its language and flags."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/transcode-audio-v2.0.0/scripts-transcode-audio-v2.0.0.tar.gz"
  sha256 "09bb1e18b14071b01d0c0e92548f9485d4ec6e31c0a7d4ddd99a7214d5597bb2"
  version "2.0.0"
  license "MIT"
  depends_on "bash"
  depends_on "ffmpeg"
  depends_on "jq"
  def install
    bin.install "transcode-audio.sh" => "transcode-audio"
    etc.install "transcode-audio.conf" => "transcode-audio.conf"
    inreplace bin/"transcode-audio", %r{^#!/usr/bin/env bash$}, "#!#{Formula["bash"].opt_bin}/bash"
  end

  test do
    assert_predicate bin/"transcode-audio", :executable?
  end
end
