# This file was generated by the package-script.sh script.
class UnlockPdf < Formula
  desc "Decrypts a password-protected PDF file using the 'qpdf' command-line tool."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/unlock-pdf-v2.0.4/scripts-unlock-pdf-v2.0.4.tar.gz"
  sha256 "1547c9b491b763b6f4ffb497dc5626c09f445c52ab0339c4d543d9df2c806bb3"
  version "2.0.4"
  license "MIT"
  depends_on "qpdf"
  def install
    bin.install "unlock-pdf.sh" => "unlock-pdf"
  end

  test do
    assert_predicate bin/"unlock-pdf", :executable?
  end
end
