# This file was generated by the package-script.sh script.
class UnlockPdf < Formula
  desc "Decrypts a password-protected PDF file using the 'qpdf' command-line tool."
  homepage "https://github.com/jmerhar/scripts"
  url "https://github.com/jmerhar/scripts/releases/download/unlock-pdf-v2.0.3/scripts-unlock-pdf-v2.0.3.tar.gz"
  sha256 "9c691525ad1129fa55185b2a0ae4e131d01ebea4aa8548805cc11649f39323f1"
  version "2.0.3"
  license "MIT"
  depends_on "qpdf"
  def install
    bin.install "unlock-pdf.sh" => "unlock-pdf"
  end

  test do
    assert_predicate bin/"unlock-pdf", :executable?
  end
end
